locale = 'en-US'
title = 'Floral Cities'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

[params.retro_footer]
  separator_image = "images/cat_separator.gif"
  lines = [
    "Best viewed in any non-Netscape browser at any resolution",
    "",
    "This work is marked CC0 1.0 Universal",
    "",
    "To use this theme, visit:",
    "https://github.com/fractuscontext/floral-cities.git"
    ]

  [[params.retro_footer.badges]]
    image = "https://jigsaw.w3.org/css-validator/images/vcss"
    alt = "Valid CSS!"
    url = "https://jigsaw.w3.org/css-validator/check/referer"

  [[params.retro_footer.badges]]
    image = "images/made_with_imac.gif"
    alt = "Best viewed on iMac"

  [[params.retro_footer.badges]]
    image = "images/pride_flag.gif"
    alt = "RAINBOW FLAG"
    url = "https://www.amnesty.org/en/what-we-do/discrimination/lgbti-rights/"

[params.header_image]
  path = "images/spinning_globe.gif"
  alt = "Spinning Earth"